# Generated by Django 4.2.1 on 2023-05-21 03:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_room_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 5, 21, 3, 7, 28, 430151, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 5, 21, 3, 7, 28, 430151, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='hotelapp.extraservice'),
        ),
    ]
