# Generated by Django 4.2.1 on 2023-05-23 18:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_extraservice_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 5, 23, 18, 4, 17, 450951, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 5, 23, 18, 4, 17, 450951, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('start_date_date',), name='unique_start_date'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('end_date_date',), name='unique_end_date'),
        ),
    ]
